const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL:
    "SET_CONTENT_OF_CONFIRM_MODAL",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
});

export default actionTypes;
